name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow only on version tags (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Publish using maturin-action
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: publish  # The maturin command to run
          token: ${{ secrets.PYPI_API_TOKEN }}
